Repository AY2324S1-CS2103T-W12-3/tp, pull requests merged in 2023-10, with the labels that each got.

#21 Update AboutUs.md
  docs/AboutUs.md
  docs/team/migfoo02.md
Labels: type.Task, priority.High

#25 Add Remark Command
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#28 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
Labels: type.Story, priority.High

#48 Add Deadline Command to ApplicationBook
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/application/logic/Messages.java
  src/main/java/seedu/application/logic/commands/DeadlineCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/job/Deadline.java
  src/main/java/seedu/application/model/job/Job.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/storage/JsonAdaptedJob.java
  src/main/java/seedu/application/ui/JobCard.java
  src/main/resources/view/JobListCard.fxml
  src/test/data/JsonSerializableApplicationBookTest/duplicateJobApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/typicalJobsApplicationBook.json
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/application/logic/parser/ApplicationBookParserTest.java
  src/test/java/seedu/application/logic/parser/DeadlineCommandParserTest.java
  src/test/java/seedu/application/model/job/JobTest.java
  src/test/java/seedu/application/storage/JsonAdaptedJobTest.java
  src/test/java/seedu/application/testutil/JobBuilder.java
  src/test/java/seedu/application/testutil/TypicalJobs.java
Labels: priority.High

#60 Logic: Add Job Type field and make Status editable
  src/main/java/seedu/application/logic/Messages.java
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/UserPrefs.java
  src/main/java/seedu/application/model/job/Job.java
  src/main/java/seedu/application/model/job/JobType.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/storage/JsonAdaptedJob.java
  src/main/java/seedu/application/storage/JsonApplicationBookStorage.java
  src/main/java/seedu/application/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/application/storage/StorageManager.java
  src/main/java/seedu/application/ui/JobCard.java
  src/main/resources/view/JobListCard.fxml
  src/test/data/JsonSerializableApplicationBookTest/duplicateJobApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/typicalJobsApplicationBook.json
  src/test/java/seedu/application/logic/LogicManagerTest.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/EditJobDescriptorTest.java
  src/test/java/seedu/application/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/application/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/application/model/job/JobTest.java
  src/test/java/seedu/application/storage/JsonAdaptedJobTest.java
  src/test/java/seedu/application/testutil/ApplicationBookBuilder.java
  src/test/java/seedu/application/testutil/EditJobDescriptorBuilder.java
  src/test/java/seedu/application/testutil/JobBuilder.java
  src/test/java/seedu/application/testutil/JobUtil.java
  src/test/java/seedu/application/testutil/TypicalJobs.java
Labels: priority.Medium

#71 Fix Job Type and test cases syntax
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/test/java/seedu/application/logic/LogicManagerTest.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandResultTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/application/logic/commands/EditCommandTest.java
  src/test/java/seedu/application/logic/commands/EditJobDescriptorTest.java
  src/test/java/seedu/application/logic/commands/ExitCommandTest.java
  src/test/java/seedu/application/logic/commands/FindCommandTest.java
  src/test/java/seedu/application/logic/commands/HelpCommandTest.java
  src/test/java/seedu/application/logic/commands/ListCommandTest.java
  src/test/java/seedu/application/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/application/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/application/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/application/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/application/model/ModelManagerTest.java
  src/test/java/seedu/application/model/job/CompanyTest.java
  src/test/java/seedu/application/model/job/FieldComparatorTest.java
  src/test/java/seedu/application/model/job/FieldContainsKeywordsPredicateTest.java
  src/test/java/seedu/application/model/job/IndustryTest.java
  src/test/java/seedu/application/model/job/JobTest.java
  src/test/java/seedu/application/model/job/JobTypeTest.java
  src/test/java/seedu/application/model/job/RoleTest.java
  src/test/java/seedu/application/model/job/StatusTest.java
  src/test/java/seedu/application/storage/JsonAdaptedJobTest.java
  src/test/java/seedu/application/testutil/JobUtil.java
  src/test/java/seedu/application/testutil/TypicalJobs.java
Labels: type.Test

#70 Add JobTypeTest.java
  src/test/java/seedu/application/model/job/JobTypeTest.java
Labels: type.Test

#68 Update ParserUtilTest
  build.gradle
  src/test/java/seedu/application/logic/parser/ParserUtilTest.java
Labels: type.Test

#80 [GUI Update] Add Job Details Panel
  src/main/java/seedu/application/Main.java
  src/main/java/seedu/application/MainApp.java
  src/main/java/seedu/application/model/job/Deadline.java
  src/main/java/seedu/application/ui/JobCard.java
  src/main/java/seedu/application/ui/JobDetailsPanel.java
  src/main/java/seedu/application/ui/JobListPanel.java
  src/main/java/seedu/application/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/JobDetailsPanel.fxml
  src/main/resources/view/JobListCard.fxml
  src/main/resources/view/JobListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/css/JobDetailsPanel.css
  src/main/resources/view/fonts/Inter-Black.ttf
  src/main/resources/view/fonts/Inter-Bold.ttf
  src/main/resources/view/fonts/Inter-ExtraBold.ttf
  src/main/resources/view/fonts/Inter-ExtraLight.ttf
  src/main/resources/view/fonts/Inter-Light.ttf
  src/main/resources/view/fonts/Inter-Medium.ttf
  src/main/resources/view/fonts/Inter-Regular.ttf
  src/main/resources/view/fonts/Inter-SemiBold.ttf
  src/main/resources/view/fonts/Inter-Thin.ttf
Labels: type.Enhancement, priority.Medium

#97 Update UG: add examples for find and sort
  docs/UserGuide.md
Labels: priority.Medium
