Repository AY2324S1-CS2103T-W12-3/tp, pull requests merged in 2023-11, with the labels that each got.

#107 Set up display of interview on GUI
  src/main/java/seedu/application/logic/LogicManager.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/ui/JobDetailsPanel.java
  src/main/java/seedu/application/ui/MainWindow.java
Labels: type.Task, priority.High

#109 Update GUI for Interview List
  docs/UserGuide.md
  src/main/java/seedu/application/ui/InterviewCard.java
  src/main/resources/view/InterviewListCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/JobDetailsPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/css/InterviewCard.css
  src/main/resources/view/css/InterviewList.css
  src/main/resources/view/css/JobCard.css
  src/main/resources/view/css/JobDetailsPanel.css
  src/main/resources/view/css/MainTheme.css
Labels: type.Enhancement

#126 Edit GUI Bug for clear command clearing job details panel
  src/main/java/seedu/application/logic/commands/ClearCommand.java
  src/main/java/seedu/application/logic/commands/CommandResult.java
  src/main/java/seedu/application/logic/commands/ExitCommand.java
  src/main/java/seedu/application/logic/commands/HelpCommand.java
  src/main/java/seedu/application/logic/commands/InterviewAddCommand.java
  src/main/java/seedu/application/logic/commands/InterviewDeleteCommand.java
  src/main/java/seedu/application/logic/commands/InterviewEditCommand.java
  src/main/java/seedu/application/model/ApplicationBook.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/ui/MainWindow.java
  src/test/java/seedu/application/logic/commands/CommandResultTest.java
  src/test/java/seedu/application/logic/commands/ExitCommandTest.java
  src/test/java/seedu/application/logic/commands/HelpCommandTest.java
Labels: type.Bug, priority.Medium

#172 Update Deadline parser to accept and convert unformatted deadline
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/job/Deadline.java
  src/test/java/seedu/application/logic/parser/ParserUtilTest.java
Labels: type.Bug

#179 Fix bug when edit job clears the respective interviews
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/job/interview/InterviewDateTime.java
Labels: type.Bug, severity.High

#195 Edit UG for edit, find and sort command
  docs/UserGuide.md
  docs/images/user-guide/EditCommandEg7.png
  docs/images/user-guide/FindCommandEg1.png
  docs/images/user-guide/FindCommandEg2.png
  docs/images/user-guide/FindCommandEg3.png
  docs/images/user-guide/FindCommandEg4.png
  docs/images/user-guide/FindCommandEg5.png
  docs/images/user-guide/QuickStartUi.png
  docs/images/user-guide/SortCommandEg1.png
  docs/images/user-guide/SortCommandEg2.png
  docs/images/user-guide/SortCommandEg3.png
  docs/images/user-guide/SortCommandEg4.png
  docs/images/user-guide/SortCommandEg5.png
  docs/images/user-guide/SortCommandEg6.png
Labels: type.Documentation

#196 [GUI Bug] Improved GUI response to commands: find, list, sort
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/ClearCommand.java
  src/main/java/seedu/application/logic/commands/CommandResult.java
  src/main/java/seedu/application/logic/commands/DeleteCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/commands/FindCommand.java
  src/main/java/seedu/application/logic/commands/ListCommand.java
  src/main/java/seedu/application/logic/commands/SortCommand.java
  src/test/java/seedu/application/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/application/logic/commands/EditCommandTest.java
  src/test/java/seedu/application/logic/commands/FindCommandTest.java
  src/test/java/seedu/application/logic/commands/ListCommandTest.java
  src/test/java/seedu/application/logic/commands/SortCommandTest.java
Labels: type.Bug, severity.Medium

#203 Edit UG description for Interview Add, Delete and Edit
  docs/UserGuide.md
  docs/images/user-guide/AddCommandEg3.png
  docs/images/user-guide/AddCommandEg4.png
  docs/images/user-guide/IntAddCommand.png
  docs/images/user-guide/IntAddCommandEg1.png
  docs/images/user-guide/IntAddCommandEg2.png
  docs/images/user-guide/IntAddCommandEg3.png
  docs/images/user-guide/IntAddCommandEg4.png
  docs/images/user-guide/IntAddCommandEg5.png
  docs/images/user-guide/IntAddCommandEg6.png
  docs/images/user-guide/IntDeleteCommand.png
  docs/images/user-guide/IntDeleteCommandEg1.png
  docs/images/user-guide/IntDeleteCommandEg2.png
  docs/images/user-guide/IntDeleteCommandEg3.png
  docs/images/user-guide/IntDeleteCommandEg4.png
  docs/images/user-guide/IntEditCommand.png
  docs/images/user-guide/IntEditCommandEg1.png
  docs/images/user-guide/IntEditCommandEg2.png
  docs/images/user-guide/IntEditCommandEg3.png
  docs/images/user-guide/IntEditCommandEg4.png
  docs/images/user-guide/IntEditCommandEg5.png
Labels: type.Documentation

#205 Update DG, index.md, README.md
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/tracing/EditCommandParserSequenceDiagram.puml
  docs/diagrams/tracing/EditCommandSequenceDiagram.puml
  docs/images/developer-guide/EditCommandParserSequenceDiagram.png
  docs/images/developer-guide/EditCommandSequenceDiagram.png
  docs/index.md
Labels: type.Documentation

#207 Update dg 3
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Testing.md
  docs/UserGuide.md
Labels: type.Documentation

#212 Edit PPP and UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/evanyan13.md
Labels: type.Documentation

#215 Update PPP & UG
  docs/UserGuide.md
  docs/team/evanyan13.md
Labels: type.Documentation
